package dms.pastor.tools.trips.tube.station;

import java.util.Arrays;

public enum Station {
    ACTON_TOWN("Acton Town"),
    ALDGATE("Aldgate"),
    ALDGATE_EAST("Aldgate East"),
    ALPERTON("Alperton"),
    AMERSHAM("Amersham"),
    ANGEL("Angel"),
    ARCHWAY("Archway"),
    ARNOS_GROVE("Arnos Grove"),
    ARSENAL("Arsenal"),
    BAKER_STREET("Baker Street"),
    BALHAM("Balham"),
    BANK("Bank"),
    BARBICAN("Barbican"),
    BARKING("Barking"),
    BARKINGSIDE("Barkingside"),
    BARONS_COURT("Barons Court"),
    BAYSWATER("Bayswater"),
    BECONTREE("Becontree"),
    BELSIZE_PARK("Belsize Park"),
    BERMONDSEY("Bermondsey"),
    BETHNAL_GREEN("Bethnal Green"),
    BLACKFRIARS("Blackfriars"),
    BLACKHORSE_ROAD("Blackhorse Road"),
    BOND_STREET("Bond Street"),
    BOROUGH("Borough"),
    BOSTON_MANOR("Boston Manor"),
    BOUNDS_GREEN("Bounds Green"),
    BOW_ROAD("Bow Road"),
    BRENT_CROSS("Brent Cross"),
    BRIXTON("Brixton"),
    BROMLEY_BY_BOW("Bromley-by-Bow"),
    BUCKHURST_HILL("Buckhurst Hill"),
    BURNT_OAK("Burnt Oak"),
    CALEDONIAN_ROAD("Caledonian Road"),
    CAMDEN_TOWN("Camden Town"),
    CANADA_WATER("Canada Water"),
    CANARY_WHARF("Canary Wharf"),
    CANNING_TOWN("Canning Town"),
    CANNON_STREET("Cannon Street"),
    CANNONS_PARK("Cannons Park"),
    CHALFONT_AND_LATIMER("Chalfont & Latimer"),
    CHALK_FARM("Chalk Farm"),
    CHANCERY_LANE("Chancery Lane"),
    CAMDEN("Camden"),
    CHARING_CROSS("Charing Cross"),
    CHESHAM("Chesham"),
    CHIGWELL("Chigwell"),
    CHISWICK_PARK("Chiswick Park"),
    CHORLEYWOOD("Chorleywood"),
    CLAPHAM_COMMON("Clapham Common"),
    CLAPHAM_NORTH("Clapham North"),
    CLAPHAM_SOUTH("Clapham South"),
    COCKFOSTERS("Cockfosters"),
    COLINDALE("Colindale"),
    COLLIERS_WOOD("Colliers Wood"),
    COVENT_GARDEN("Covent Garden"),
    CROXLEY("Croxley"),
    DAGENHAM_EAST("Dagenham East"),
    DAGENHAM_HEATHWAY("Dagenham Heathway"),
    DEBDEN("Debden"),
    DOLLIS_HILL("Dollis Hill"),
    EALING_BROADWAY("Ealing Broadway"),
    EALING_COMMON("Ealing Common"),
    EARLS_COURT("Earl's Court"),
    EAST_ACTON("East Acton"),
    EAST_FINCHLEY("East Finchley"),
    EAST_HAM("East Ham"),
    EAST_PUTNEY("East Putney"),
    EASTCOTE("Eastcote"),
    EDGWARE("Edgware"),
    EDGWARE_ROAD("Edgware Road"),
    ELEPHANT_AND_CASTLE("Elephant & Castle"),
    ELM_PARK("Elm Park"),
    EMBANKMENT("Embankment"),
    EPPING("Epping"),
    EUSTON("Euston"),
    EUSTON_SQUARE("Euston Square"),
    FAIRLOP("Fairlop"),
    FARRINGDON("Farringdon"),
    FINCHLEY_CENTRAL("Finchley Central"),
    FINCHLEY_ROAD("Finchley Road"),
    FINSBURY_PARK("Finsbury Park"),
    FULHAM_BROADWAY("Fulham Broadway"),
    GANTS_HILL("Gants Hill"),
    GLOUCESTER_ROAD("Gloucester Road"),
    GOLDERS_GREEN("Golders Green"),
    GOLDHAWK_ROAD("Goldhawk Road"),
    GOODGE_STREET("Goodge Street"),
    GRANGE_HILL("Grange Hill"),
    GREAT_PORTLAND_STREET("Great Portland Street"),
    GREENFORD("Greenford"),
    GREEN_PARK("Green Park"),
    GUNNERSBURY("Gunnersbury"),
    HAINAULT("Hainault"),
    HAMMERSMITH("Hammersmith"),
    HAMPSTEAD("Hampstead"),
    HANGER_LANE("Hanger Lane"),
    HARLESDEN("Harlesden"),
    HARROW_AND_WEALDSTONE("Harrow & Wealdstone"),
    HARROW_ON_THE_HILL("Harrow-on-the-Hill"),
    HATTON_CROSS("Hatton Cross"),
    HEATHROW_TERMINALS_1_2_3("Heathrow Terminals 1, 2, 3"),
    HEATHROW_TERMINAL_4("Heathrow Terminal 4"),
    HEATHROW_TERMINAL_5("Heathrow Terminal 5"),
    HENDON_CENTRAL("Hendon Central"),
    HIGH_BARNET("High Barnet"),
    HIGHBURY_AND_ISLINGTON("Highbury & Islington"),
    HIGHGATE("Highgate"),
    HIGH_STREET_KENSINGTON("High Street Kensington"),
    HILLINGDON("Hillingdon"),
    HOLBORN("Holborn"),
    HOLLAND_PARK("Holland Park"),
    HOLLOWAY_ROAD("Holloway Road"),
    HORNCHURCH("Hornchurch"),
    HOUNSLOW_CENTRAL("Hounslow Central"),
    HOUNSLOW_EAST("Hounslow East"),
    HOUNSLOW_WEST("Hounslow West"),
    HYDE_PARK_CORNER("Hyde Park Corner"),
    ICKENHAM("Ickenham"),
    KENNINGTON("Kennington"),
    KENSAL_GREEN("Kensal Green"),
    KENSINGTON_OLYMPIA("KENSINGTON (Olympia)"),
    KENTISH_TOWN("Kentish Town"),
    KENTON("Kenton"),
    HARROW("Harrow"),
    KEW_GARDENS("Kew Gardens"),
    KILBURN("Kilburn"),
    KILBURN_PARK("Kilburn Park"),
    KINGSBURY("Kingsbury"),
    KINGS_CROSS_ST_PANCRAS("King's Cross St. Pancras"),
    KNIGHTSBRIDGE("Knightsbridge"),
    LADBROKE_GROVE("Ladbroke Grove"),
    LAMBETH_NORTH("Lambeth North"),
    LANCASTER_GATE("Lancaster Gate"),
    LATIMER_ROAD("Latimer Road"),
    LEICESTER_SQUARE("Leicester Square"),
    LEYTON("Leyton"),
    LEYTONSTONE("Leytonstone"),
    LIVERPOOL_STREET("Liverpool Street"),
    LONDON_BRIDGE("London Bridge"),
    LOUGHTON("Loughton"),
    MAIDA_VALE("Maida Vale"),
    MANOR_HOUSE("Manor House"),
    MANSION_HOUSE("Mansion House"),
    MARBLE_ARCH("Marble Arch"),
    MARYLEBONE("Marylebone"),
    MILE_END("Mile End"),
    MILL_HILL_EAST("Mill Hill East"),
    MONUMENT("Monument"),
    MOORGATE("Moorgate"),
    MOOR_PARK("Moor Park"),
    MORDEN("Morden"),
    MORNINGTON_CRESCENT("Mornington Crescent"),
    NEASDEN("Neasden"),
    NEWBURY_PARK("Newbury Park"),
    NORTH_ACTON("North Acton"),
    NORTH_EALING("North Ealing"),
    NORTH_GREENWICH("North Greenwich"),
    NORTH_HARROW("North Harrow"),
    NORTH_WEMBLEY("North Wembley"),
    NORTHFIELDS("Northfields"),
    NORTHOLT("Northolt"),
    NORTHWICK_PARK("Northwick Park"),
    NORTHWOOD("Northwood"),
    NORTHWOOD_HILLS("Northwood Hills"),
    NOTTING_HILL_GATE("Notting Hill Gate"),
    OAKWOOD("Oakwood"),
    OLD_STREET("Old Street"),
    OSTERLEY("Osterley"),
    OVAL("Oval"),
    OXFORD_CIRCUS("Oxford Circus"),
    PADDINGTON("Paddington"),
    PARK_ROYAL("Park Royal"),
    PARSONS_GREEN("Parsons Green"),
    PERIVALE("Perivale"),
    PICCADILLY_CIRCUS("Piccadilly Circus"),
    PIMLICO("Pimlico"),
    PINNER("Pinner"),
    PLAISTOW("Plaistow"),
    PRESTON_ROAD("Preston Road"),
    PUTNEY_BRIDGE("Putney Bridge"),
    QUEENS_PARK("Queen's Park"),
    QUEENSBURY("Queensbury"),
    QUEENSWAY("Queensway"),
    RAVENSCOURT_PARK("Ravenscourt Park"),
    RAYNERS_LANE("Rayners Lane"),
    REDBRIDGE("Redbridge"),
    REGENTS_PARK("Regent's Park"),
    RICHMOND("Richmond"),
    RICKMANSWORTH("Rickmansworth"),
    RODING_VALLEY("Roding Valley"),
    ROYAL_OAK("Royal Oak"),
    RUISLIP("Ruislip"),
    RUISLIP_GARDENS("Ruislip Gardens"),
    RUISLIP_MANOR("Ruislip Manor"),
    RUSSELL_SQUARE("Russell Square"),
    ST_JAMESS_PARK("St. James's Park"),
    ST_JOHNS_WOOD("St. John's Wood"),
    ST_PAULS("St. Paul's"),
    SEVEN_SISTERS("Seven Sisters"),
    SHEPHERDS_BUSH("Shepherd's Bush"),
    SHEPHERDS_BUSH_MARKET("Shepherd's Bush Market"),
    SLOANE_SQUARE("Sloane Square"),
    SNARESBROOK("Snaresbrook"),
    SOUTH_EALING("South Ealing"),
    SOUTH_HARROW("South Harrow"),
    SOUTH_KENSINGTON("South Kensington"),
    SOUTH_KENTON("South Kenton"),
    SOUTH_RUISLIP("South Ruislip"),
    SOUTH_WIMBLEDON("South Wimbledon"),
    SOUTH_WOODFORD("South Woodford"),
    SOUTHFIELDS("Southfields"),
    SOUTHGATE("Southgate"),
    SOUTHWARK("Southwark"),
    STAMFORD_BROOK("Stamford Brook"),
    STANMORE("Stanmore"),
    STEPNEY_GREEN("Stepney Green"),
    STOCKWELL("Stockwell"),
    STONEBRIDGE_PARK("Stonebridge Park"),
    STRATFORD("Stratford"),
    SUDBURY_HILL("Sudbury Hill"),
    SUDBURY_TOWN("Sudbury Town"),
    EALING("Ealing"),
    SWISS_COTTAGE("Swiss Cottage"),
    TEMPLE("Temple"),
    THEYDON_BOIS("Theydon Bois"),
    TOOTING_BEC("Tooting Bec"),
    TOOTING_BROADWAY("Tooting Broadway"),
    TOTTENHAM_COURT_ROAD("Tottenham Court Road"),
    TOTTENHAM_HALE("Tottenham Hale"),
    TOTTERIDGE_AND_WHETSTONE("Totteridge & Whetstone"),
    TOWER_HILL("Tower Hill"),
    TUFNELL_PARK("Tufnell Park"),
    TURNHAM_GREEN("Turnham Green"),
    TURNPIKE_LANE("Turnpike Lane"),
    UPMINSTER("Upminster"),
    UPMINSTER_BRIDGE("Upminster Bridge"),
    UPNEY("Upney"),
    UPTON_PARK("Upton Park"),
    UXBRIDGE("Uxbridge"),
    VAUXHALL("Vauxhall"),
    VICTORIA("Victoria"),
    WALTHAMSTOW_CENTRAL("Walthamstow Central"),
    WANSTEAD("Wanstead"),
    WARREN_STREET("Warren Street"),
    WARWICK_AVENUE("Warwick Avenue"),
    WATERLOO("Waterloo"),
    WATFORD("Watford"),
    WEMBLEY_CENTRAL("Wembley Central"),
    WEMBLEY_PARK("Wembley Park"),
    WEST_ACTON("West Acton"),
    WEST_BROMPTON("West Brompton"),
    WEST_FINCHLEY("West Finchley"),
    WEST_HAM("West Ham"),
    WEST_HAMPSTEAD("West Hampstead"),
    WEST_HARROW("West Harrow"),
    WEST_KENSINGTON("West Kensington"),
    WEST_RUISLIP("West Ruislip"),
    WESTBOURNE_PARK("Westbourne Park"),
    WESTMINSTER("Westminster"),
    WHITE_CITY("White City"),
    WHITECHAPEL("Whitechapel"),
    WILLESDEN_GREEN("Willesden Green"),
    WILLESDEN_JUNCTION("Willesden Junction"),
    WIMBLEDON("Wimbledon"),
    WIMBLEDON_PARK("Wimbledon Park"),
    WOOD_GREEN("Wood Green"),
    WOOD_LANE("Wood Lane"),
    WOODFORD("Woodford"),
    WOODSIDE_PARK("Woodside Park");

    private final String stationName;

    Station(String stationName) {
        this.stationName = stationName;
    }

    public static boolean has(String stationName) {
        return Arrays.asList(Station.values()).stream().anyMatch(it -> it.getStationName().equalsIgnoreCase(stationName));
    }

    public String getStationName() {
        return stationName;
    }
}
