package dms.pastor.examples.java15;

//tag-text-block-example
@SuppressWarnings("SameReturnValue")
public class TextBlockExample {

    public static String getAutoGeneratedMultiLineString() {
        return "Java\n\tfinally\n\tsupport\n\tmulti-line";
    }
}

