package dms.pastor.tools.nanobackup.GUI;

import org.apache.commons.io.FileUtils;
import org.apache.commons.io.IOUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URI;
import java.util.Properties;

/**
 * About window where are displayed information about me, program, changelog, eula and thanks
 *
 * @author dominik symonowicz
 * <p>
 * Created on 2009-10-31, 17:59:32
 */
public class About extends javax.swing.JFrame {

    private static final Logger LOGGER = LoggerFactory.getLogger(About.class);
    private final Properties properties = new Properties();
    // Variables declaration - do not modify
    // End of variables declaration
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AboutTabbedPanel;
    private javax.swing.JLabel JVLabel;
    private javax.swing.JLabel OSLabel;
    private javax.swing.JPanel aboutMePanel;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JPanel changelogPanel;
    private javax.swing.JTextArea changelogTextArea;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel eulaPanel;
    private javax.swing.JTextArea eulaTextArea;
    private javax.swing.JButton goToButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lincenceLabel;
    private javax.swing.JScrollPane messagePanel;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel pictureOfMe;
    private javax.swing.JPanel thanksPanel;
    private javax.swing.JScrollPane thanksScrollPanel;
    private javax.swing.JTextArea thanksTextArea;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JTextField www;
    private javax.swing.JLabel wwwLabel;

    /**
     * About constructor that run setup to set/load all data necessary to display everything
     */
    public About() {
        setup();
        initComponents();
    }

    /**
     * Run about indend
     *
     * @param args
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new About().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AboutTabbedPanel = new javax.swing.JTabbedPane();
        aboutPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        lincenceLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        OSLabel = new javax.swing.JLabel();
        JVLabel = new javax.swing.JLabel();
        changelogPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        changelogTextArea = new javax.swing.JTextArea();
        aboutMePanel = new javax.swing.JPanel();
        authorLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        wwwLabel = new javax.swing.JLabel();
        www = new javax.swing.JTextField();
        messagePanel = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        goToButton = new javax.swing.JButton();
        pictureOfMe = new javax.swing.JLabel();
        thanksPanel = new javax.swing.JPanel();
        thanksScrollPanel = new javax.swing.JScrollPane();
        thanksTextArea = new javax.swing.JTextArea();
        eulaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eulaTextArea = new javax.swing.JTextArea();

        setTitle("ABOUT ME");
        setAlwaysOnTop(true);
        setName("about"); // NOI18N
        setResizable(false);

        AboutTabbedPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutTabbedPanelMouseClicked(evt);
            }
        });

        nameLabel.setText("NAME: nanoBackup");

        versionLabel.setText(properties.getProperty("about.version"));

        lincenceLabel.setText("FORM OF SOFTWARE DISTRIBUTION: Freeware");

        jScrollPane5.setEnabled(false);
        jScrollPane5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText(properties.getProperty("about.program"));
        jTextArea2.setWrapStyleWord(true);
        jScrollPane5.setViewportView(jTextArea2);

        OSLabel.setText("OS: " + System.getProperty("os.name") + "[" + System.getProperty("os.version") + "/" + System.getProperty("os.arch") + "]");

        JVLabel.setText("JAVA: " + System.getProperty("java.version"));

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
                aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(aboutPanelLayout.createSequentialGroup()
                                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameLabel)
                                        .addComponent(versionLabel)
                                        .addComponent(lincenceLabel)
                                        .addComponent(OSLabel)
                                        .addComponent(JVLabel)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE))
                                .addContainerGap())
        );
        aboutPanelLayout.setVerticalGroup(
                aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(aboutPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(versionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lincenceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(OSLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JVLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
        );

        AboutTabbedPanel.addTab("About program", aboutPanel);

        changelogTextArea.setColumns(20);
        changelogTextArea.setEditable(false);
        changelogTextArea.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        changelogTextArea.setLineWrap(true);
        changelogTextArea.setRows(5);
        changelogTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(changelogTextArea);

        javax.swing.GroupLayout changelogPanelLayout = new javax.swing.GroupLayout(changelogPanel);
        changelogPanel.setLayout(changelogPanelLayout);
        changelogPanelLayout.setHorizontalGroup(
                changelogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        changelogPanelLayout.setVerticalGroup(
                changelogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        AboutTabbedPanel.addTab("changelog", changelogPanel);

        authorLabel.setText("Author: Dominik Symonowicz");

        emailLabel.setText("Email:");

        emailField.setEditable(false);
        emailField.setText("dmspastor@gmail.com");

        wwwLabel.setText("www:");

        www.setEditable(false);
        www.setText("http://pastor.ovh.org");

        messageTextArea.setColumns(20);
        messageTextArea.setEditable(false);
        messageTextArea.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        messageTextArea.setLineWrap(true);
        messageTextArea.setRows(5);
        messageTextArea.setText(properties.getProperty("about.me"));
        messagePanel.setViewportView(messageTextArea);

        goToButton.setText("Go to my page");
        goToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToButtonActionPerformed(evt);
            }
        });

        pictureOfMe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanobackup/me.jpg"))); // NOI18N

        javax.swing.GroupLayout aboutMePanelLayout = new javax.swing.GroupLayout(aboutMePanel);
        aboutMePanel.setLayout(aboutMePanelLayout);
        aboutMePanelLayout.setHorizontalGroup(
                aboutMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(aboutMePanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(pictureOfMe, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(aboutMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(authorLabel)
                                        .addGroup(aboutMePanelLayout.createSequentialGroup()
                                                .addComponent(emailLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                                        .addComponent(messagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                        .addGroup(aboutMePanelLayout.createSequentialGroup()
                                                .addComponent(wwwLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(www, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(goToButton)))
                                .addContainerGap())
        );
        aboutMePanelLayout.setVerticalGroup(
                aboutMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(aboutMePanelLayout.createSequentialGroup()
                                .addGroup(aboutMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(aboutMePanelLayout.createSequentialGroup()
                                                .addComponent(authorLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(aboutMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(emailLabel)
                                                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(aboutMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(aboutMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(www, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(goToButton))
                                                        .addComponent(wwwLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(messagePanel))
                                        .addComponent(pictureOfMe, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        AboutTabbedPanel.addTab("About me", aboutMePanel);

        thanksTextArea.setColumns(20);
        thanksTextArea.setEditable(false);
        thanksTextArea.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        thanksTextArea.setLineWrap(true);
        thanksTextArea.setRows(5);
        thanksTextArea.setText(properties.getProperty("about.thanks"));
        thanksTextArea.setWrapStyleWord(true);
        thanksScrollPanel.setViewportView(thanksTextArea);

        javax.swing.GroupLayout thanksPanelLayout = new javax.swing.GroupLayout(thanksPanel);
        thanksPanel.setLayout(thanksPanelLayout);
        thanksPanelLayout.setHorizontalGroup(
                thanksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(thanksScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        thanksPanelLayout.setVerticalGroup(
                thanksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(thanksScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        AboutTabbedPanel.addTab("Thanks", thanksPanel);

        eulaTextArea.setColumns(20);
        eulaTextArea.setEditable(false);
        eulaTextArea.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        eulaTextArea.setLineWrap(true);
        eulaTextArea.setRows(5);
        jScrollPane1.setViewportView(eulaTextArea);

        javax.swing.GroupLayout eulaPanelLayout = new javax.swing.GroupLayout(eulaPanel);
        eulaPanel.setLayout(eulaPanelLayout);
        eulaPanelLayout.setHorizontalGroup(
                eulaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        eulaPanelLayout.setVerticalGroup(
                eulaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        AboutTabbedPanel.addTab("eula", eulaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AboutTabbedPanel)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AboutTabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AboutTabbedPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutTabbedPanelMouseClicked
        try {
            String changelog = FileUtils.readFileToString(new File("data" + System.getProperty("file.separator") + "changelog.txt"));
            changelogTextArea.setText(changelog);
            changelogTextArea.setCaretPosition(0);
            String eula = FileUtils.readFileToString(new File("data" + System.getProperty("file.separator") + "eula.txt"));
            eulaTextArea.setText(eula);
            eulaTextArea.setCaretPosition(0);
        } catch (IOException ex) {
            LOGGER.warn("IOException occur during clicking on tab" + ex.getMessage());
        }
    }//GEN-LAST:event_AboutTabbedPanelMouseClicked

    private void goToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToButtonActionPerformed
        try {
            java.awt.Desktop.getDesktop().browse(new URI("http://pastor.ovh.org"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "It is something wrong with web address.\nPossible reasons:\nIt is possible that you have weird problem with internet connection.\nFirewall blocks Java to access to inernet\nAddress is incorrect.", "BAD NEWS!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_goToButtonActionPerformed
    // End of variables declaration//GEN-END:variables

    private void setup() {
        FileInputStream fis = null;
        try {
            fis = new FileInputStream("data" + System.getProperty("file.separator") + "message.properties");
            properties.load(fis);
        } catch (FileNotFoundException ex) {
            LOGGER.warn("Unexpected error due load properties for About." + ex.getCause() + ("\n" + ex.getMessage()));
            JOptionPane.showMessageDialog(rootPane, messagePanel, "WOOPS", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        } catch (IOException ex) {
            LOGGER.warn("Unexpected error due load properties for About." + ex.getCause() + ("\n" + ex.getMessage()));
            this.dispose();
        } finally {
            IOUtils.closeQuietly(fis);
        }
    }
}
